# Toolchain image: OCaml (opam), Alpine/musl.
#
# opam is statically linked; opam-repository is a git repository (git cache).
ARG BASE_IMAGE=toolchain-base:alpine-3.24
FROM ${BASE_IMAGE}
COPY cache/opam-2.6.0-x86_64-linux /usr/local/bin/opam
RUN chmod +x /usr/local/bin/opam
ENV OPAMROOT=/opt/opam
RUN opam --version
