# Toolchain image: Clojure (clojure CLI / tools.deps), Alpine/musl.
ARG BASE_IMAGE=toolchain-java:alpine-3.24
FROM ${BASE_IMAGE}
COPY cache/clojure-tools-1.12.6.1673.tar.gz /tmp/clojure.tar.gz
RUN set -eux; \
    tar -xzf /tmp/clojure.tar.gz -C /tmp && rm /tmp/clojure.tar.gz; \
    cd /tmp/clojure-tools; \
    prefix=/usr/local; \
    install -d "$prefix/libexec" "$prefix/bin"; \
    cp ./*.jar "$prefix/libexec/"; \
    cp deps.edn example-deps.edn tools.edn "$prefix"/; \
    sed -e "s#PREFIX#$prefix#g" clojure > "$prefix/bin/clojure"; \
    sed -e "s#BINDIR#$prefix/bin#g" clj > "$prefix/bin/clj"; \
    chmod 755 "$prefix/bin/clojure" "$prefix/bin/clj"; \
    cd /; rm -rf /tmp/clojure-tools
ENV PATH=/usr/local/bin:$PATH
RUN clojure -Sdescribe >/dev/null && echo clojure-ok
